### ISSUE TITLE
can not run with python 3.6

### ISSUE THREAD

**Issue by pc10201** [peterldowns/lggr#12]
windows 10 python 3.6

Traceback (most recent call last):
  File "D:\Python3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\Python3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "S:\test.py", line 1, in <module>
    import lggr
  File "D:\Python3\lib\site-packages\lggr\__init__.py", line 11, in <module>
    from lggr.coroutine import coroutine, coroutine_process, coroutine_thread
  File "D:\Python3\lib\site-packages\lggr\coroutine.py", line 4, in <module>
    import Queue
ModuleNotFoundError: No module named 'Queue'

**Comment by peterldowns** [comment]
Thanks for submitting this – should be a simple matter of rewriting the imports. If you submit a PR I'll review as soon as I can, but I'm travelling right now so I hope you'll bear with me.
